# Generated by Django 4.0.3 on 2022-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('CatID', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, max_length=1, null=True)),
                ('Parent', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCategoryValues',
            fields=[
                ('CatValID', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.CharField(blank=True, max_length=1200, null=True)),
                ('Status', models.CharField(blank=True, max_length=1, null=True)),
                ('SortOrder', models.IntegerField(blank=True, null=True)),
                ('CatID', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=600, null=True)),
                ('ParentID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
